export const FETCH_COCKTAILS_FROM_API_START = 'FETCH_COCKTAILS_FROM_API_START';
export const FETCH_COCKTAILS_FROM_API_SUCCESS = 'FETCH_COCKTAILS_FROM_API_SUCCESS';
export const FETCH_COCKTAILS_FROM_API_FAIL = 'FETCH_COCKTAILS_FROM_API_FAIL';